### ISSUE TITLE
Issue with INDELS in vcf file

### ISSUE THREAD

**Issue by Swap90** [santiagosnchez/vcf2fasta#1]
The perl script does not consider INDELS. If there is an INDEL in VCF file, it is not reflected in output fasta file. Can you please advise on this issue ?

Thanks
Swapnil

**Comment by santiagosnchez** [comment]
Sorry for the super late reply. Somehow I overlooked this. The Perl version currently can't deal with INDELS, it only works on SNPs. The Python version should be able to handle INDELs – check it out!

**Comment by jiazhiyuan123** [comment]
the perl script can work, but i can't get fasta file, when the script was done, i have nothing file. can you help me?

**Comment by santiagosnchez** [comment]
I'm currently doing a major overhaul of the Python version. Hopefully it will be ready soon.

**Comment by santiagosnchez** [comment]
Please try the new Python version. It should work with indels and vcf file of various kinds such as haploid, diploid, phased, unphased (iupac).
