### ISSUE TITLE
KeyError: 'Sample1_1': Dealing Samples with missing genotype calls

### ISSUE THREAD

**Issue by VJ-Ulaganathan** [santiagosnchez/vcf2fasta#12]
Hi @santiagosnchez 
I merged multiple sample files, but noticed that for some samples the genotype information is omitted/missing and bcftools cannot add `0/0`. This is shown as "`.:.:.:.:.:.:.:.:.:.:.:.:.:. `" instead of " `0/0:.:.:.:.:.:.:.:.:.:.:.:.:. `" 

For instance, here is a data with and without genotype calls.

`chr10	42600747	42600747	T	A	.	PASS	ADP=266;HET=1;HOM=0;NC=0;SF=1;WT=0;customer_score1=chr10;customer_score2=42600747;AN=32;AC=12	GT:RBQ:ADF:FREQ:ABQ:RDR:GQ:SDP:RD:RDF:AD:DP:ADR:PVAL	0/1:38:94:62.78%:40:38:255:266:99:61:167:266:73:4.3167E-68	0/1:39:56:62.9%:39:41:255:186:69:28:117:186:61:6.4215E-48	.:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.	0/1:37:100:65.62%:38:31:255:256:88:57:168:256:68:9.3353E-70	.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/1:37:103:66.17%:38:36:255:269:90:54:178:269:75:2.9185E-741/1:35:95:77.5%:37:15:255:200:45:30:155:200:60:3.5483E-70	0/1:38:122:68.03%:39:32:255:319:102:70:217:319:95:2.1692E-91	.:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/1:36:74:65.79%:39:23:255:228:78:55:150:228:76:2.0634E-62	0/1:39:85:68.24%:40:22:255:233:74:52:159:233:74:3.2552E-67	0/1:36:94:68.48%:39:33:255:276:87:54:189:276:95:6.4253E-80	.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/1:38:80:71.43%:38:23:255:210:60:37:150:210:70:7.1812E-65	0/1:38:79:62.76%:40:41:255:239:88:47:150:239:71:2.5852E-61`

I think because of this, I get the following error when I execute the vcf2fasta.py script.

```
Traceback (most recent call last):
  File "/media/Desktop/RawGenotypingData/vcf2fasta-master/vcf2fasta.py", line 515, in <module>
    main()
  File "/media/Desktop/RawGenotypingData/vcf2fasta-master/vcf2fasta.py", line 139, in main
    sequences,varsites,codon_start,strand = getSequences(gff, gene, args.feat, args.blend, args.inframe, ref, vcf, ploidy, phased, samples, args.addref)
  File "/media/Desktop/RawGenotypingData/vcf2fasta-master/vcf2fasta.py", line 215, in getSequences
    tmpseqs[sample] = UpdateSeq(alleles, sample, pos, ref_len, tmpseqs[sample])
KeyError: 'Sample1_1'
```

****Would it be possible for you to please edit the script to ignore if `0/0` genotype information is missing for certain "samples"??** **

The first two entries are as follows, output of  `zcat merged.vcf.gz | head -n150`

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample-1	Sample-2	Sample-3	Sample-4	Sample-5	Sample-7	Sample-8	Sample-9	Sample-10	Sample-11	Sample-12	Sample-13	Sample-14	Sample-15	Sample-16	Sample-17	Sample-18	Sample-19	Sample-20	Sample-21	Sample-22	Sample-23	Sample-24	Sample-25	Sample-27	Sample-28	Sample-29	Sample-30
chr10	60074	.	G	C	.	PASS	ADP=10;HET=1;HOM=0;NC=0;SF=1;WT=0;AN=25;AC=0	GT:ADR:RDF:ABQ:DP:FREQ:ADF:RBQ:PVAL:SDP:AD:GQ:RDR:RD	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:..:.:.:.:.:.:.:.:.:.:.:.:.:.	.:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.	0:.:.:.:.:.:.:.:.:.:.:.:.:.
chr10	60164	.	G	A	39.77	PASS	ADP=37;DP=20;DPB=20;EPPR=4.51363;GTI=0;HET=1;HOM=0;MQMR=27;NC=0;NS=1;NUMALT=1;ODDS=9.15713;PAIREDR=1;PQR=0;PRO=0;QR=512;RO=13;RPPR=4.51363;SF=0,1;SRF=13;SRP=31.2394;SRR=0;WT=0;AB=0.35;ABP=6.91895;AF=0.5;AO=7;DPRA=0;EPP=3.32051;LEN=1;MEANALT=1;MQM=27;PAIRED=1;PAO=0;PQA=0;QA=254;RPL=3;RPP=3.32051;RPR=4;RUN=1;SAF=7;SAP=18.2106;SAR=0;AN=56;AC=1	GT:FREQ:DP:GQ:RBQ:ADF:ADR:QR:SDP:GL:PVAL:RDR:QA:AO:RDF:AD:ABQ:RD:RO	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/1:.:20:.:.:.:.:512:.:-10.3416,0,-25.4805:.:.:254:7:.:.:.:.:13	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.


```

**Comment by santiagosnchez** [comment]
Hi Vijay,

Can you remind me if these are supposed to be somatic mutations? If they are, I think that the genotype field should be recoded into a "haploid" genotype. For example, have "1", instead of "0/1". Otherwise, the program will "think" that these is germline diploid data. So say, you have a "0/1" call for REF "T" and ALT "C", the script will turn this into a "Y" thinking that it is a germline polymorphism. But if you have "1", it will turn it into a haploid "C".

For the missing data, you can leave just as "." if you chance all mutations to haploid "1".

Also bear in mind that you will be constructing chimeric sequences, since different mutations will be coming from different cells/haplotypes without phase info.

Let me know if this makes sense to you or if you keep having trouble.

**Comment by VJ-Ulaganathan** [comment]
Hi Santiago,
many thanks for your response.
These are supposed to be germline polymorphism and not somatic mutation, so relatively easy to interpret I guess.
Perhaps, this is an issue if genotype information is missing on merged file.
I have no problem running vcf2fasta.py on individiual sample files, but when I merge them into single file, I have the issue of missing genotype data for some samples. Because the polymorphisms are at different loci for different samples.
Can you please help on how to fix this error?

```
Traceback (most recent call last):
  File "/media/Desktop/RawGenotypingData/vcf2fasta-master/vcf2fasta.py", line 515, in <module>
    main()
  File "/media/Desktop/RawGenotypingData/vcf2fasta-master/vcf2fasta.py", line 139, in main
    sequences,varsites,codon_start,strand = getSequences(gff, gene, args.feat, args.blend, args.inframe, ref, vcf, ploidy, phased, samples, args.addref)
  File "/media/Desktop/RawGenotypingData/vcf2fasta-master/vcf2fasta.py", line 215, in getSequences
    tmpseqs[sample] = UpdateSeq(alleles, sample, pos, ref_len, tmpseqs[sample])
KeyError: 'Sample1_1'
```

Many thanks
Vijay

**Comment by VJ-Ulaganathan** [comment]
I figured that in the merged vcf file, sample 14 had diploid genotype 2/2.
Upon closed examination of the full merged file, i noticed there are several diploid genotype that were not converted to haploid 
This actually was the issue, and  if I convert all diploid to haploid, the problem is solved. So I close this issue.

**Comment by santiagosnchez** [comment]
Hi @VJ-Ulaganathan, sorry I couldn't help you figure this out sooner, but glad that you did!
