### ISSUE TITLE
GFF structure

### ISSUE THREAD

**Issue by qhelleu** [santiagosnchez/vcf2fasta#2]
Hey, 
vcf2fasta.py is very efficient and doing a great job. But, to make it even better and easier to use, I would recommand to make it compatible with the most common GFF3 format: gene > mRNA > CDS and not gene > CDS. 
Also, it would be nice to integrate an automatic reverse complement for CDS on the '-' strand. 

Thanks for the great job,
Best,
Quentin

**Comment by santiagosnchez** [comment]
Hi Quentin,

Thanks for the compliment! I've added some fixes to the GFF structure reading step, which may some some of the previous issues. There was also a bug preventing the reverse complement step which is now resolved. The current version should now give you RC sequences automatically.

Let me know if you are still having issues.
