### ISSUE TITLE
chromosome name

### ISSUE THREAD

**Issue by wcfgit** [santiagosnchez/vcf2fasta#4]
Dear Santiago,
first of all thank you for providing this really useful script!

Maybe just as a reminder for future users, it would be good to mention that chromosome names should be in a specific format e.g. with just numbers.

I had my VCF file, GFF and FASTA with chromosome names as e.g. "chr_1" and it was giving me KeyError.
After changing the chromosome names just to number it worked out perfectly. 

Thank you.

**Comment by santiagosnchez** [comment]
Good to hear you found it useful! For the record, the `vcf2fasta` not specifically require a certain format for chromosome/scaffold names. However, it does require consistency across your files, i.e. VCF, GFF, and FASTA ref must have the same string names for each chromosome. I'm guessing in your case there was probably a slight inconsistency that you solved by changing to numbers (perhaps the GFF?).
