### ISSUE TITLE
KeyError: g1

### ISSUE THREAD

**Issue by VJ-Ulaganathan** [santiagosnchez/vcf2fasta#7]
While trying to execute the script, for the files provided in the "example" folder,

I get the following error,

python vcf2fasta.py -f reference -v test_file_haploid.vcf.gz -g gff_file.gff -feat -e CDS --blend -o OUT

Reading GFF file [gff_file.gff] ... Traceback (most recent call last):
  File "vcf2fasta.py", line 515, in <module>
    main()
  File "vcf2fasta.py", line 78, in main
    gff = filterFeatureInGFF(ReadGFF(args.gff), args.feat)
  File "vcf2fasta.py", line 453, in ReadGFF
    gff[last['Name']][fields[2]].append(fields)
KeyError: 'g1'

Can you please help on resolving this issue?
Many thanks
Vijay

**Comment by VJ-Ulaganathan** [comment]
This is resolved if I use GTF file.

**Comment by matthewglasenapp** [comment]
@VJ-Ulaganathan Where did you find the GTF file?
